package com.xrk.usd.dal.entity;

// Generated 2015-9-7 18:09:32 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

/**
 * UgsGrowingType generated by hbm2java
 */
@Entity
@Table(name = "ugs_growing_type", schema = "public")
//@NamedQueries({
//	@NamedQuery(name="growingType.findAll", 
//							query="SELECT c FROM UgsGrowingType c"),
//	@NamedQuery(name="growingType.findByCode", 
//							query="SELECT c FROM UgsGrowingType c WHERE c.typeCode=:typeCode")
// @NamedQuery(name="growingType.update", 
//							query="UPDATE UgsGrowingType SET typeName=:typeName, status=:status WHERE typeCode=:typeCode")
//})
public class UgsGrowingType implements java.io.Serializable {
    private static final long serialVersionUID = 1L;
	private String typeCode;
	private String typeName;
	private short status;
	private Set<UgsGrowingRuleGroup> ugsGrowingRuleGroups = new HashSet<UgsGrowingRuleGroup>(0);
	private Set<UgsPointType> ugsPointTypes = new HashSet<UgsPointType>(0);
	private UgsGrowingActiveGroup ugsGrwoingActiveGroup;
	private Set<UgsUserGradeConfig> ugsUserGradeConfigs = new HashSet<UgsUserGradeConfig>(0);
	private Set<UgsUserInfo> ugsUserInfos = new HashSet<UgsUserInfo>(0);

	public UgsGrowingType() {
	}

	public UgsGrowingType(String typeCode, String typeName, short status) {
		this.typeCode = typeCode.toUpperCase();
		this.typeName = typeName;
		this.status = status;
	}

	public UgsGrowingType(String typeCode, String typeName, short status,
			Set<UgsGrowingRuleGroup> ugsGrowingRuleGroups, Set<UgsPointType> ugsPointTypes,
			UgsGrowingActiveGroup ugsGrwoingActiveGroup,
			Set<UgsUserGradeConfig> ugsUserGradeConfigs, Set<UgsUserInfo> ugsUserInfos) {
		this.typeCode = typeCode.toUpperCase();
		this.typeName = typeName;
		this.status = status;
		this.ugsGrowingRuleGroups = ugsGrowingRuleGroups;
		this.ugsPointTypes = ugsPointTypes;
		this.ugsGrwoingActiveGroup = ugsGrwoingActiveGroup;
		this.ugsUserGradeConfigs = ugsUserGradeConfigs;
		this.ugsUserInfos = ugsUserInfos;
	}

	@Id
	@Column(name = "type_code", unique = true, nullable = false, length = 30)
	public String getTypeCode() {
		return this.typeCode;
	}

	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode.toUpperCase();
	}

	@Column(name = "type_name", nullable = false, length = 60)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Column(name = "status", nullable = false)
	public short getStatus() {
		return this.status;
	}

	public void setStatus(short status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ugsGrowingType")
	public Set<UgsGrowingRuleGroup> getUgsGrowingRuleGroups() {
		return this.ugsGrowingRuleGroups;
	}

	public void setUgsGrowingRuleGroups(Set<UgsGrowingRuleGroup> ugsGrowingRuleGroups) {
		this.ugsGrowingRuleGroups = ugsGrowingRuleGroups;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ugsGrowingType")
	public Set<UgsPointType> getUgsPointTypes() {
		return this.ugsPointTypes;
	}

	public void setUgsPointTypes(Set<UgsPointType> ugsPointTypes) {
		this.ugsPointTypes = ugsPointTypes;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "ugsGrowingType")
	public UgsGrowingActiveGroup getUgsGrwoingActiveGroup() {
		return this.ugsGrwoingActiveGroup;
	}

	public void setUgsGrwoingActiveGroup(
			UgsGrowingActiveGroup ugsGrwoingActiveGroup) {
		this.ugsGrwoingActiveGroup = ugsGrwoingActiveGroup;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ugsGrowingType")
	public Set<UgsUserGradeConfig> getUgsUserGradeConfigs() {
		return this.ugsUserGradeConfigs;
	}

	public void setUgsUserGradeConfigs(Set<UgsUserGradeConfig> ugsUserGradeConfigs) {
		this.ugsUserGradeConfigs = ugsUserGradeConfigs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ugsGrowingType")
	public Set<UgsUserInfo> getUgsUserInfos() {
		return this.ugsUserInfos;
	}

	public void setUgsUserInfos(Set<UgsUserInfo> ugsUserInfos) {
		this.ugsUserInfos = ugsUserInfos;
	}

}
