package com.xrk.usd.dal.entity;

// Generated 2015-9-7 18:09:32 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * UgsGrowingRuleGroup generated by hbm2java
 */
@Entity
@Table(name = "ugs_growing_rule_group", schema = "public")
public class UgsGrowingRuleGroup implements java.io.Serializable {

    public static final short STATUS_NEW = 0;             //新建
    public static final short STATUS_AUDIT_FAILURE = 10;  //审核失败
    public static final short STATUS_FOR_AUDIT = 1;       //等待审核
    public static final short STATUS_NORMAL = 2;          //可使用
    public static final short STATUS_FORBIDDEN = 3;       //禁止
    public static final short STATUS_DELETED = 4;         //已删除

	private static final long serialVersionUID = 1L;
	private int ruleGroupId;
	private UgsGrowingType ugsGrowingType;
	private String ruleGroupName;
	private short status;
	private Set<UgsGrowingRuleList> ugsGrowingRuleLists = new HashSet<UgsGrowingRuleList>(0);
	private Set<UgsProcessLog> ugsProcessLogs = new HashSet<UgsProcessLog>(0);
	private Set<UgsGrowingActiveGroup> ugsGrwoingActiveGroups = new HashSet<UgsGrowingActiveGroup>(0);

	public UgsGrowingRuleGroup() {
	}

	public UgsGrowingRuleGroup(int ruleGroupId, UgsGrowingType ugsGrowingType,
			String ruleGroupName, short status) {
		this.ruleGroupId = ruleGroupId;
		this.ugsGrowingType = ugsGrowingType;
		this.ruleGroupName = ruleGroupName;
		this.status = status;
	}

	public UgsGrowingRuleGroup(int ruleGroupId, UgsGrowingType ugsGrowingType,
			String ruleGroupName, short status, Set<UgsGrowingRuleList> ugsGrowingRuleLists,
			Set<UgsProcessLog> ugsProcessLogs, Set<UgsGrowingActiveGroup> ugsGrwoingActiveGroups) {
		this.ruleGroupId = ruleGroupId;
		this.ugsGrowingType = ugsGrowingType;
		this.ruleGroupName = ruleGroupName;
		this.status = status;
		this.ugsGrowingRuleLists = ugsGrowingRuleLists;
		this.ugsProcessLogs = ugsProcessLogs;
		this.ugsGrwoingActiveGroups = ugsGrwoingActiveGroups;
	}

	@Id
	@SequenceGenerator(name="rule-group-seq-gen",sequenceName="ugs_growing_rule_group_rule_group_id_seq", allocationSize=1)
	@GeneratedValue(strategy= GenerationType.SEQUENCE, generator="rule-group-seq-gen")
	@Column(name = "rule_group_id", unique = true, nullable = false)
	public int getRuleGroupId() {
		return this.ruleGroupId;
	}

	public void setRuleGroupId(int ruleGroupId) {
		this.ruleGroupId = ruleGroupId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type_code", nullable = false)
	public UgsGrowingType getUgsGrowingType() {
		return this.ugsGrowingType;
	}

	public void setUgsGrowingType(UgsGrowingType ugsGrowingType) {
		this.ugsGrowingType = ugsGrowingType;
	}

	@Column(name = "rule_group_name", nullable = false, length = 60)
	public String getRuleGroupName() {
		return this.ruleGroupName;
	}

	public void setRuleGroupName(String ruleGroupName) {
		this.ruleGroupName = ruleGroupName;
	}

	@Column(name = "status", nullable = false)
	public short getStatus() {
		return this.status;
	}

	public void setStatus(short status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ugsGrowingRuleGroup")
	public Set<UgsGrowingRuleList> getUgsGrowingRuleLists() {
		return this.ugsGrowingRuleLists;
	}

	public void setUgsGrowingRuleLists(Set<UgsGrowingRuleList> ugsGrowingRuleLists) {
		this.ugsGrowingRuleLists = ugsGrowingRuleLists;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ugsGrowingRuleGroup")
	public Set<UgsProcessLog> getUgsProcessLogs() {
		return this.ugsProcessLogs;
	}

	public void setUgsProcessLogs(Set<UgsProcessLog> ugsProcessLogs) {
		this.ugsProcessLogs = ugsProcessLogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ugsGrowingRuleGroup", targetEntity = UgsGrowingActiveGroup.class)
	public Set<UgsGrowingActiveGroup> getUgsGrwoingActiveGroups() {
		return this.ugsGrwoingActiveGroups;
	}

	public void setUgsGrwoingActiveGroups(Set<UgsGrowingActiveGroup> ugsGrwoingActiveGroups) {
		this.ugsGrwoingActiveGroups = ugsGrwoingActiveGroups;
	}

}
