package com.xrk.usd.dal.entity;

// Generated 2015-9-7 18:09:32 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UgsGrowingRuleParameter generated by hbm2java
 */
@Entity
@Table(name = "ugs_growing_rule_parameter", schema = "public")
public class UgsGrowingRuleParameter implements java.io.Serializable {
    private static final long serialVersionUID = 1L;
	private UgsGrowingRuleParameterId id;
	private UgsGrowingRuleList ugsGrowingRuleList;
	private String paramValue;

	public UgsGrowingRuleParameter() {
	}

	public UgsGrowingRuleParameter(UgsGrowingRuleParameterId id,
			UgsGrowingRuleList ugsGrowingRuleList, String paramValue) {
		this.id = id;
		this.ugsGrowingRuleList = ugsGrowingRuleList;
		this.paramValue = paramValue;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "ruleListId", column = @Column(name = "rule_list_id", nullable = false)),
			@AttributeOverride(name = "paramName", column = @Column(name = "param_name", nullable = false, length = 50)) })
	public UgsGrowingRuleParameterId getId() {
		return this.id;
	}

	public void setId(UgsGrowingRuleParameterId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rule_list_id", nullable = false, insertable = false, updatable = false)
	public UgsGrowingRuleList getUgsGrowingRuleList() {
		return this.ugsGrowingRuleList;
	}

	public void setUgsGrowingRuleList(UgsGrowingRuleList ugsGrowingRuleList) {
		this.ugsGrowingRuleList = ugsGrowingRuleList;
	}

	@Column(name = "param_value", nullable = false)
	public String getParamValue() {
		return this.paramValue;
	}

	public void setParamValue(String paramValue) {
		this.paramValue = paramValue;
	}

}
