package com.xrk.usd.dal.entity;

// Generated 2015-9-7 18:09:32 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UgsObserver generated by hbm2java
 */
@Entity
@Table(name = "ugs_observer", schema = "public")
public class UgsObserver implements java.io.Serializable {
    private static final long serialVersionUID = 1L;
	private int observerId;
	private String clientName;
	private String subscibe;
	private String callbackUrl;
	private String clientIp;
	private Date addDate;

	public UgsObserver() {
	}

	public UgsObserver(int observerId, String clientName, String subscibe,
			String callbackUrl) {
		this.observerId = observerId;
		this.clientName = clientName;
		this.subscibe = subscibe;
		this.callbackUrl = callbackUrl;
	}

	public UgsObserver(int observerId, String clientName, String subscibe,
			String callbackUrl, String clientIp, Date addDate) {
		this.observerId = observerId;
		this.clientName = clientName;
		this.subscibe = subscibe;
		this.callbackUrl = callbackUrl;
		this.clientIp = clientIp;
		this.addDate = addDate;
	}

	@Id
	@SequenceGenerator(name="observer-seq-gen",sequenceName="ugs_observer_observer_id_seq", allocationSize=1)
	@GeneratedValue(strategy= GenerationType.SEQUENCE, generator="observer-seq-gen")
	@Column(name = "observer_id", unique = true, nullable = false)
	public int getObserverId() {
		return this.observerId;
	}

	public void setObserverId(int observerId) {
		this.observerId = observerId;
	}

	@Column(name = "client_name", nullable = false, length = 100)
	public String getClientName() {
		return this.clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	@Column(name = "subscibe", nullable = false, length = 200)
	public String getSubscibe() {
		return this.subscibe;
	}

	public void setSubscibe(String subscibe) {
		this.subscibe = subscibe;
	}

	@Column(name = "callback_url", nullable = false, length = 200)
	public String getCallbackUrl() {
		return this.callbackUrl;
	}

	public void setCallbackUrl(String callbackUrl) {
		this.callbackUrl = callbackUrl;
	}

	@Column(name = "client_ip", length = 20)
	public String getClientIp() {
		return this.clientIp;
	}

	public void setClientIp(String clientIp) {
		this.clientIp = clientIp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "add_date", length = 29)
	public Date getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Date addDate) {
		this.addDate = addDate;
	}

}
