package com.xrk.usd.dal.entity;

// Generated 2015-9-7 18:09:32 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * UgsPointType generated by hbm2java
 */
@Entity
@Table(name = "ugs_point_type", schema = "public")
public class UgsPointType implements java.io.Serializable {
    private static final long serialVersionUID = 1L;
	private int pointTypeId;
	private UgsGrowingType ugsGrowingType;
	private String pointTypeCode;
	private String pointTypeName;
	private Set<UgsUserGradeConfig> ugsUserGradeConfigs = new HashSet<UgsUserGradeConfig>(0);
	private Set<UgsUserPoint> ugsUserPoints = new HashSet<UgsUserPoint>(0);

	public UgsPointType() {
	}

	public UgsPointType(int pointTypeId, UgsGrowingType ugsGrowingType,
			String pointTypeCode, String pointTypeName) {
		this.pointTypeId = pointTypeId;
		this.ugsGrowingType = ugsGrowingType;
		this.pointTypeCode = pointTypeCode;
		this.pointTypeName = pointTypeName;
	}

	public UgsPointType(int pointTypeId, UgsGrowingType ugsGrowingType,
			String pointTypeCode, String pointTypeName,
			Set<UgsUserGradeConfig> ugsUserGradeConfigs, Set<UgsUserPoint> ugsUserPoints) {
		this.pointTypeId = pointTypeId;
		this.ugsGrowingType = ugsGrowingType;
		this.pointTypeCode = pointTypeCode;
		this.pointTypeName = pointTypeName;
		this.ugsUserGradeConfigs = ugsUserGradeConfigs;
		this.ugsUserPoints = ugsUserPoints;
	}

	@Id
    @SequenceGenerator(name="point-type-seq-gen",sequenceName="ugs_point_type_point_type_id_seq", allocationSize=1)
    @GeneratedValue(strategy= GenerationType.SEQUENCE, generator="point-type-seq-gen")
	@Column(name = "point_type_id", unique = true, nullable = false)
	public int getPointTypeId() {
		return this.pointTypeId;
	}

	public void setPointTypeId(int pointTypeId) {
		this.pointTypeId = pointTypeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type_code", nullable = false)
	public UgsGrowingType getUgsGrowingType() {
		return this.ugsGrowingType;
	}

	public void setUgsGrowingType(UgsGrowingType ugsGrowingType) {
		this.ugsGrowingType = ugsGrowingType;
	}

	@Column(name = "point_type_code", nullable = false, length = 30)
	public String getPointTypeCode() {
		return this.pointTypeCode;
	}

	public void setPointTypeCode(String pointTypeCode) {
		this.pointTypeCode = pointTypeCode;
	}

	@Column(name = "point_type_name", nullable = false, length = 60)
	public String getPointTypeName() {
		return this.pointTypeName;
	}

	public void setPointTypeName(String pointTypeName) {
		this.pointTypeName = pointTypeName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ugsPointType")
	public Set<UgsUserGradeConfig> getUgsUserGradeConfigs() {
		return this.ugsUserGradeConfigs;
	}

	public void setUgsUserGradeConfigs(Set<UgsUserGradeConfig> ugsUserGradeConfigs) {
		this.ugsUserGradeConfigs = ugsUserGradeConfigs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ugsPointType")
	public Set<UgsUserPoint> getUgsUserPoints() {
		return this.ugsUserPoints;
	}

	public void setUgsUserPoints(Set<UgsUserPoint> ugsUserPoints) {
		this.ugsUserPoints = ugsUserPoints;
	}

}
