package com.xrk.usd.dal.entity;

// Generated 2015-9-7 18:09:32 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.*;

/**
 * UgsProcessLog generated by hbm2java
 */
@Entity
@Table(name = "ugs_process_log", schema = "public")
public class UgsProcessLog implements java.io.Serializable {
    private static final long serialVersionUID = 1L;
	private int logId;
	private UgsGrowingRuleGroup ugsGrowingRuleGroup;
	private Date addDate;
	private String userName;
	private String description;

	public UgsProcessLog() {
	}

	public UgsProcessLog(int logId, UgsGrowingRuleGroup ugsGrowingRuleGroup,
			Date addDate) {
		this.logId = logId;
		this.ugsGrowingRuleGroup = ugsGrowingRuleGroup;
		this.addDate = addDate;
	}

	public UgsProcessLog(int logId, UgsGrowingRuleGroup ugsGrowingRuleGroup,
			Date addDate, String userName, String description) {
		this.logId = logId;
		this.ugsGrowingRuleGroup = ugsGrowingRuleGroup;
		this.addDate = addDate;
		this.userName = userName;
		this.description = description;
	}

	@Id
    @SequenceGenerator(name="log-seq-gen",sequenceName="ugs_point_type_point_type_id_seq", allocationSize=1)
    @GeneratedValue(strategy= GenerationType.SEQUENCE, generator="log-seq-gen")
	@Column(name = "log_id", unique = true, nullable = false)
	public int getLogId() {
		return this.logId;
	}

	public void setLogId(int logId) {
		this.logId = logId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rule_group_id", nullable = false)
	public UgsGrowingRuleGroup getUgsGrowingRuleGroup() {
		return this.ugsGrowingRuleGroup;
	}

	public void setUgsGrowingRuleGroup(UgsGrowingRuleGroup ugsGrowingRuleGroup) {
		this.ugsGrowingRuleGroup = ugsGrowingRuleGroup;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "add_date", nullable = false, length = 13)
	public Date getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Date addDate) {
		this.addDate = addDate;
	}

	@Column(name = "user_name", length = 100)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
