package com.xrk.usd.dal.entity;

// Generated 2015-9-7 18:09:32 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UgsUserGradeConfigList generated by hbm2java
 */
@Entity
@Table(name = "ugs_user_grade_config_list", schema = "public")
public class UgsUserGradeConfigList implements java.io.Serializable {
    private static final long serialVersionUID = 1L;
	private UgsUserGradeConfigListId id;
	private UgsUserGradeConfig ugsUserGradeConfig;
	private int point;

	public UgsUserGradeConfigList() {
	}

	public UgsUserGradeConfigList(UgsUserGradeConfigListId id,
			UgsUserGradeConfig ugsUserGradeConfig, int point) {
		this.id = id;
		this.ugsUserGradeConfig = ugsUserGradeConfig;
		this.point = point;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "gradeId", column = @Column(name = "grade_id", nullable = false)),
			@AttributeOverride(name = "level", column = @Column(name = "level", nullable = false)) })
	public UgsUserGradeConfigListId getId() {
		return this.id;
	}

	public void setId(UgsUserGradeConfigListId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "grade_id", nullable = false, insertable = false, updatable = false)
	public UgsUserGradeConfig getUgsUserGradeConfig() {
		return this.ugsUserGradeConfig;
	}

	public void setUgsUserGradeConfig(UgsUserGradeConfig ugsUserGradeConfig) {
		this.ugsUserGradeConfig = ugsUserGradeConfig;
	}

	@Column(name = "point", nullable = false)
	public int getPoint() {
		return this.point;
	}

	public void setPoint(int point) {
		this.point = point;
	}

}
