package com.xrk.usd.dal.entity;

// Generated 2015-9-7 18:09:32 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UgsUserPoint generated by hbm2java
 */
@Entity
@Table(name = "ugs_user_point", schema = "public")
public class UgsUserPoint implements java.io.Serializable {
    private static final long serialVersionUID = 1L;
	private UgsUserPointId id;
	private UgsPointType ugsPointType;
	private UgsUserInfo ugsUserInfo;
	private int point;
	private Date editDate;

	public UgsUserPoint() {
	}

	public UgsUserPoint(UgsUserPointId id, UgsPointType ugsPointType,
			UgsUserInfo ugsUserInfo, int point, Date editDate) {
		this.id = id;
		this.ugsPointType = ugsPointType;
		this.ugsUserInfo = ugsUserInfo;
		this.point = point;
		this.editDate = editDate;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "uidSeq", column = @Column(name = "uid_seq", nullable = false)),
			@AttributeOverride(name = "pointTypeId", column = @Column(name = "point_type_id", nullable = false)) })
	public UgsUserPointId getId() {
		return this.id;
	}

	public void setId(UgsUserPointId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "point_type_id", nullable = false, insertable = false, updatable = false)
	public UgsPointType getUgsPointType() {
		return this.ugsPointType;
	}

	public void setUgsPointType(UgsPointType ugsPointType) {
		this.ugsPointType = ugsPointType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "uid_seq", nullable = false, insertable = false, updatable = false)
	public UgsUserInfo getUgsUserInfo() {
		return this.ugsUserInfo;
	}

	public void setUgsUserInfo(UgsUserInfo ugsUserInfo) {
		this.ugsUserInfo = ugsUserInfo;
	}

	@Column(name = "point", nullable = false)
	public int getPoint() {
		return this.point;
	}

	public void setPoint(int point) {
		this.point = point;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "edit_date", nullable = false, length = 29)
	public Date getEditDate() {
		return this.editDate;
	}

	public void setEditDate(Date editDate) {
		this.editDate = editDate;
	}

}
