package com.xrk.usd.dal.entity;

// Generated 2015-9-7 18:09:32 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UgsUserPointId generated by hbm2java
 */
@Embeddable
public class UgsUserPointId implements java.io.Serializable {
    private static final long serialVersionUID = 1L;
	private long uidSeq;
	private int pointTypeId;

	public UgsUserPointId() {
	}

	public UgsUserPointId(long uidSeq, int pointTypeId) {
		this.uidSeq = uidSeq;
		this.pointTypeId = pointTypeId;
	}

	@Column(name = "uid_seq", nullable = false)
	public long getUidSeq() {
		return this.uidSeq;
	}

	public void setUidSeq(long uidSeq) {
		this.uidSeq = uidSeq;
	}

	@Column(name = "point_type_id", nullable = false)
	public int getPointTypeId() {
		return this.pointTypeId;
	}

	public void setPointTypeId(int pointTypeId) {
		this.pointTypeId = pointTypeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UgsUserPointId))
			return false;
		UgsUserPointId castOther = (UgsUserPointId) other;

		return (this.getUidSeq() == castOther.getUidSeq())
				&& (this.getPointTypeId() == castOther.getPointTypeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUidSeq();
		result = 37 * result + this.getPointTypeId();
		return result;
	}

}
