package com.xrk.usd.dal.entity;

// Generated 2015-9-7 18:09:32 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UgsUserGradeConfigListId generated by hbm2java
 */
@Embeddable
public class UgsUserGradeConfigListId implements java.io.Serializable {
    private static final long serialVersionUID = 1L;
	private int gradeId;
	private short level;

	public UgsUserGradeConfigListId() {
	}

	public UgsUserGradeConfigListId(int gradeId, short level) {
		this.gradeId = gradeId;
		this.level = level;
	}

	@Column(name = "grade_id", nullable = false)
	public int getGradeId() {
		return this.gradeId;
	}

	public void setGradeId(int gradeId) {
		this.gradeId = gradeId;
	}

	@Column(name = "level", nullable = false)
	public short getLevel() {
		return this.level;
	}

	public void setLevel(short level) {
		this.level = level;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UgsUserGradeConfigListId))
			return false;
		UgsUserGradeConfigListId castOther = (UgsUserGradeConfigListId) other;

		return (this.getGradeId() == castOther.getGradeId())
				&& (this.getLevel() == castOther.getLevel());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getGradeId();
		result = 37 * result + this.getLevel();
		return result;
	}

}
