package com.xrk.usd.dal.entity;

// Generated 2015-9-7 18:09:32 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * UgsUserInfo generated by hbm2java
 */
@Entity
@Table(name = "ugs_user_info", schema = "public")
public class UgsUserInfo implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
	private long uidSeqId;
	private UgsGrowingType ugsGrowingType;
	private long uid;
	private Date addDate;
	private Set<UgsUserPoint> ugsUserPoints = new HashSet<UgsUserPoint>(0);
	private Set<UgsUserPointHistory> ugsUserPointHistories = new HashSet<UgsUserPointHistory>(0);

	public UgsUserInfo() {
	}

	public UgsUserInfo(long uidSeqId, UgsGrowingType ugsGrowingType, long uid,
			Date addDate) {
		this.uidSeqId = uidSeqId;
		this.ugsGrowingType = ugsGrowingType;
		this.uid = uid;
		this.addDate = addDate;
	}

	public UgsUserInfo(long uidSeqId, UgsGrowingType ugsGrowingType, long uid,
			Date addDate, Set<UgsUserPoint> ugsUserPoints, Set<UgsUserPointHistory> ugsUserPointHistories) {
		this.uidSeqId = uidSeqId;
		this.ugsGrowingType = ugsGrowingType;
		this.uid = uid;
		this.addDate = addDate;
		this.ugsUserPoints = ugsUserPoints;
		this.ugsUserPointHistories = ugsUserPointHistories;
	}

	@Id
	@SequenceGenerator(name="ugs_user_info_uid_seq_id",sequenceName="ugs_user_info_uid_seq_id_seq", allocationSize=1)
	@GeneratedValue(strategy= GenerationType.SEQUENCE, generator="ugs_user_info_uid_seq_id")
	@Column(name = "uid_seq_id", unique = true, nullable = false)
	public long getUidSeqId() {
		return this.uidSeqId;
	}

	public void setUidSeqId(long uidSeqId) {
		this.uidSeqId = uidSeqId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type_code", nullable = false)
	public UgsGrowingType getUgsGrowingType() {
		return this.ugsGrowingType;
	}

	public void setUgsGrowingType(UgsGrowingType ugsGrowingType) {
		this.ugsGrowingType = ugsGrowingType;
	}

	@Column(name = "uid", nullable = false)
	public long getUid() {
		return this.uid;
	}

	public void setUid(long uid) {
		this.uid = uid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "add_date", nullable = false, length = 29)
	public Date getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Date addDate) {
		this.addDate = addDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ugsUserInfo")
	public Set<UgsUserPoint> getUgsUserPoints() {
		return this.ugsUserPoints;
	}

	public void setUgsUserPoints(Set<UgsUserPoint> ugsUserPoints) {
		this.ugsUserPoints = ugsUserPoints;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ugsUserInfo")
	public Set<UgsUserPointHistory> getUgsUserPointHistories() {
		return this.ugsUserPointHistories;
	}

	public void setUgsUserPointHistories(Set<UgsUserPointHistory> ugsUserPointHistories) {
		this.ugsUserPointHistories = ugsUserPointHistories;
	}

}
