package com.xrk.usd.dal.entity;

// Generated 2015-9-7 18:09:32 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.*;

/**
 * UgsUserPointHistory generated by hbm2java
 */
@Entity
@Table(name = "ugs_user_point_history", schema = "public")
public class UgsUserPointHistory implements java.io.Serializable {
    private static final long serialVersionUID = 1L;
	private int historyId;
	private UgsUserInfo ugsUserInfo;
	private Date addDate;
	private String ruleCode;
	private String ruleName;
	private String typeCode;
	private String typeName;
	private int point;
	private String description;

	public UgsUserPointHistory() {
	}

	public UgsUserPointHistory(int historyId, UgsUserInfo ugsUserInfo,
			Date addDate, String ruleCode, String ruleName, int point) {
		this.historyId = historyId;
		this.ugsUserInfo = ugsUserInfo;
		this.addDate = addDate;
		this.ruleCode = ruleCode;
		this.ruleName = ruleName;
		this.point = point;
	}

	public UgsUserPointHistory(int historyId, UgsUserInfo ugsUserInfo,
			Date addDate, String ruleCode, String ruleName, int point,
			String description) {
		this.historyId = historyId;
		this.ugsUserInfo = ugsUserInfo;
		this.addDate = addDate;
		this.ruleCode = ruleCode;
		this.ruleName = ruleName;
		this.point = point;
		this.description = description;
	}

	@Id
	@SequenceGenerator(name="ugs_user_point_history_history_id",sequenceName="ugs_user_point_history_history_id_seq", allocationSize=1)
	@GeneratedValue(strategy= GenerationType.SEQUENCE, generator="ugs_user_point_history_history_id")
	@Column(name = "history_id", unique = true, nullable = false)
	public int getHistoryId() {
		return this.historyId;
	}

	public void setHistoryId(int historyId) {
		this.historyId = historyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "uid_seq", nullable = false)
	public UgsUserInfo getUgsUserInfo() {
		return this.ugsUserInfo;
	}

	public void setUgsUserInfo(UgsUserInfo ugsUserInfo) {
		this.ugsUserInfo = ugsUserInfo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "add_date", nullable = false, length = 29)
	public Date getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Date addDate) {
		this.addDate = addDate;
	}

	@Column(name = "type_code", nullable = false, length = 50)
	public String getTypeCode() {
		return this.typeCode;
	}

	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode;
	}

	@Column(name = "type_name", nullable = false, length = 100)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Column(name = "rule_code", nullable = false, length = 50)
	public String getRuleCode() {
		return this.ruleCode;
	}

	public void setRuleCode(String ruleCode) {
		this.ruleCode = ruleCode;
	}

	@Column(name = "rule_name", nullable = false, length = 100)
	public String getRuleName() {
		return this.ruleName;
	}

	public void setRuleName(String ruleName) {
		this.ruleName = ruleName;
	}

	@Column(name = "point", nullable = false)
	public int getPoint() {
		return this.point;
	}

	public void setPoint(int point) {
		this.point = point;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
